use_frameworks!

platform :ios, '8.0'

target 'BMLongPressDragCellCollectionView_Example' do
  pod 'BMLongPressDragCellCollectionView', :path => '../'

  target 'BMLongPressDragCellCollectionView_Tests' do
    inherit! :search_paths
  end
end
